# Generated by Django 4.1.1 on 2022-12-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player_registration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="player_registration_form",
            name="role",
            field=models.CharField(default="LHB", max_length=50),
        ),
    ]
